# Set the current review czar
czar: C2Redhat

# Set the backup czar for pull requests authored by czar
backup: bjohnsto

# Triage assignment reference
triage: C2Redhat
triage-next: bjohnsto

# A list of possible triage, review czar and backup assignees
members:
  - C2Redhat
  - bjohnsto
  - raeburn
  - slegendr

# Members of the team in an advisory role
advisory-members:
  - lorelei-sakai
  - rhawalsh
