# Set the current review czar
czar: C2Redhat

# Set the backup czar for pull requests authored by czar
backup: raeburn

# Triage assignment reference
triage: cchung
triage-next: raeburn

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  slegendr:
    Role: rotation
    Jira: slegendr
    Github: slegendr
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 20-Feb | cchung      | raeburn
# 30-Jan | bjohnsto    | cchung
# 07-Feb | bjohnsto    | raeburn
# 20-Feb | cchung      | raeburn
# 05-Mar | raeburn     | slegendr
# 19-Mar | slegendr    | bjohnsto
# 02-Apr | bjohnsto    | cchung
# 16-Apr | cchung      | raeburn
# 30-Apr | raeburn     | slegendr
# 14-May | slegendr    | bjohnsto
