# Set the current review czar
czar: slegendr

# Set the backup czar for pull requests authored by czar
backup: bjohnsto

# Triage assignment reference
triage: slegendr
triage-next: bjohnsto

# A list of possible triage, review czar and backup assignees
members:
  bjohnsto:
    Jira: bjohnston
    Github: bjohnsto
  cchung:
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Jira: raeburn
    Github: raeburn
  slegendr:
    Jira: slegendr
    Github: slegendr

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 16-Jan | slegendr    | bjohnsto
# 30-Jan | bjohnsto    | cchung
# 13-Feb | cchung      | raeburn
# 27-Feb | raeburn     | slegendr
# 12-Mar | slegendr    | bjohnsto
# 26-Mar | bjohnsto    | cchung
# 09-Apr | cchung      | raeburn
# 16-Apr | raeburn     | slegendr

# Members of the team in an advisory role
advisory-members:
  msakai:
    Github: lorelei-sakai
    Jira: msakai
  awalsh:
    Github: rhawalsh
    Jira: awalsh
