# Set the current review czar
czar: slegendr

# Set the backup czar for pull requests authored by czar
backup: bjohnsto

# Triage assignment reference
triage: slegendr
triage-next: bjohnsto

# A list of possible triage, review czar and backup assignees
members:
  - bjohnsto
  - C2Redhat
  - raeburn
  - slegendr

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 24-Oct | slegendr    | bjohnsto
# 07-Nov | bjohnsto    | C2Redhat
# 21-Nov | C2Redhat    | raeburn
# 05-Dec | raeburn     | slegendr
# 19-Dec | slegendr    | bjohnsto
# 02-Jan | bjohnsto    | C2Redhat
# 16-Jan | C2Redhat    | raeburn

# Members of the team in an advisory role
advisory-members:
  - lorelei-sakai
  - rhawalsh
