# Set the current review czar
czar: slegendr

# Set the backup czar for pull requests authored by czar
backup: bjohnsto

# Triage assignment reference
triage: slegendr
triage-next: bjohnsto

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  slegendr:
    Role: rotation
    Jira: slegendr
    Github: slegendr
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# If running on the first date listed below, the following command will generate the new appropriate dates:
#   count=0; i=14; while [ $count -lt 8 ]; do date -d "+${i}days" +"%d-%b"; i=$((i+14)); count=$((count+1)); done
# Date   | triage/czar | backup
# -------+-------------+----------
# 02-Jul | slegendr    | bjohnsto
# 30-Jul | bjohnsto    | cchung
# 13-Aug | cchung      | raeburn
# 27-Aug | raeburn     | slegendr
# 10-Sep | slegendr    | bjohnsto
# 24-Sep | bjohnsto    | cchung
# 08-Oct | cchung      | raeburn
# 22-Oct | raeburn     | slegendr
