# Set the current review czar
czar: bjohnsto

# Set the backup czar for pull requests authored by czar
backup: lorelei-sakai

# A list of possible review czars and backups
members:
  - bjohnsto  
  - lorelei-sakai
  - raeburn
  - slegendr


