# Set the current review czar
czar: raeburn

# Set the backup czar for pull requests authored by czar
backup: slegendr

# Triage assignment reference
triage: raeburn
triage-next: slegendr

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  slegendr:
    Role: rotation
    Jira: slegendr
    Github: slegendr
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 12-Mar | raeburn     | slegendr
# 26-Mar | slegendr    | bjohnsto
# 02-Apr | bjohnsto    | cchung
# 16-Apr | cchung      | raeburn
# 30-Apr | raeburn     | slegendr
# 14-May | slegendr    | bjohnsto
# 28-May | bjohnsto    | cchung
# 11-Jun | cchung      | raeburn
# 25-Jun | raeburn     | slegendr
