# Set the current review czar
czar: bjohnsto

# Set the backup czar for pull requests authored by czar
backup: jshimkus-rh

# A list of possible review czars and backups
members:
  - bjohnsto
  - jochapma
  - jshimkus-rh


