# Set the current review czar
# (This must refer to the Github value of the assignee)
czar: C2Redhat

# Set the backup czar for pull requests authored by czar
# (This must refer to the Github value of the assignee)
backup: raeburn

# Triage assignment reference
triage: cchung
triage-next: raeburn

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# If running on the first date listed below, the following command will generate the new appropriate dates:
#   count=0; i=14; while [ $count -lt 8 ]; do date -d "+${i}days" +"%d-%b"; i=$((i+14)); count=$((count+1)); done
# Date   | triage/czar | backup
# -------+-------------+----------
# 07-Oct | bjohnsto    | cchung
# 21-Oct | cchung      | raeburn
# 04-Nov | raeburn     | bjohnsto
# 18-Nov | bjohnsto    | cchung
# 02-Dec | cchung      | raeburn
# 16-Dec | raeburn     | bjohnsto
# 30-Dec | bjohnsto    | cchung
# 13-Jan | cchung      | raeburn
