# Set the current review czar
# (This must refer to the Github value of the assignee)
czar: raeburn

# Set the backup czar for pull requests authored by czar
# (This must refer to the Github value of the assignee)
backup: bjohnsto

# Triage assignment reference
triage: raeburn
triage-next: bjohnsto

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# If running on the first date listed below, the following command will generate the new appropriate dates:
#   count=0; i=14; while [ $count -lt 8 ]; do date -d "+${i}days" +"%d-%b"; i=$((i+14)); count=$((count+1)); done
# Date   | triage/czar | backup
# -------+-------------+----------
# 10-Dec | raeburn     | bjohnsto
# 02-Jan | bjohnsto    | cchung
# 14-Jan | cchung      | raeburn
# 28-Jan | raeburn     | bjohnsto
# 11-Feb | bjohnsto    | cchung
# 25-Feb | cchung      | raeburn
# 11-Mar | raeburn     | bjohnsto
# 25-Mar | bjohnsto    | cchung
