# Set the current review czar
czar: raeburn

# Set the backup czar for pull requests authored by czar
backup: selegendr

# Triage assignment reference
triage: raeburn
triage-next: slegendr

# A list of possible triage, review czar and backup assignees
members:
  - bjohnsto
  - C2Redhat
  - raeburn
  - slegendr

# Members of the team in an advisory role
advisory-members:
  - lorelei-sakai
  - rhawalsh
