# Set the current review czar
czar: slegendr

# Set the backup czar for pull requests authored by czar
backup: cchung

# Triage assignment reference
triage: slegendr
triage-next: cchung

# A list of possible triage, review czar and backup assignees
members:
  - bjohnsto
  - C2Redhat
  - raeburn
  - slegendr

# Members of the team in an advisory role
advisory-members:
  - lorelei-sakai
  - rhawalsh
