# Set the current review czar
czar: bjohnsto

# Set the backup czar for pull requests authored by czar
backup: cchung

# Triage assignment reference
triage: bjohnsto
triage-next: cchung

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: rojohnst
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  slegendr:
    Role: rotation
    Jira: slegendr
    Github: slegendr
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 30-Jan | bjohnsto    | cchung
# 13-Feb | cchung      | raeburn
# 27-Feb | raeburn     | slegendr
# 12-Mar | slegendr    | bjohnsto
# 26-Mar | bjohnsto    | cchung
# 09-Apr | cchung      | raeburn
# 16-Apr | raeburn     | slegendr
# 30-Apr | slegendr    | bjohnsto
