# Set the current review czar
czar: C2Redhat

# Set the backup czar for pull requests authored by czar
backup: raeburn

# Triage assignment reference
triage: cchung
triage-next: raeburn

# A list of possible triage, review czar and backup assignees
members:
  bjohnsto:
    Jira: bjohnston
    Github: bjohnsto
  cchung:
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Jira: raeburn
    Github: raeburn
  slegendr:
    Jira: slegendr
    Github: slegendr

# Upcoming rotation:
# Date   | triage/czar | backup
# -------+-------------+----------
# 21-Nov | C2Redhat    | raeburn
# 02-Jan | raeburn     | slegendr
# 16-Jan | slegendr    | bjohnsto
# 30-Jan | bjohnsto    | C2Redhat
# 13-Feb | C2Redhat    | raeburn
# 27-Feb | raeburn     | slegendr
# 12-Mar | slegendr    | bjohnsto
# 26-Mar | bjohnsto    | C2Redhat

# Members of the team in an advisory role
advisory-members:
  msakai:
    Github: lorelei-sakai
    Jira: msakai
  awalsh:
    Github: rhawalsh
    Jira: awalsh
