name: 'VDO Auto Assign PR'
description: 'Auto assigns reviewers and assignees to VDO PRs'
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
